services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    command: ["php", "artisan", "serve", "--host=0.0.0.0", "--port=8000"]

  db-viewer:
    image: coleifer/sqlite-web
    restart: unless-stopped
    environment:
      SQLITE_DATABASE: database.sqlite
    ports:
      - "8080:8080"
    volumes:
      - ./backend/database:/data
